# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ yarn_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - yarn-install-dependencies
