# tasks file
---
- name: repository | install dependencies (pre)
  ansible.builtin.apt:
    name: "{{ yarn_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - yarn-repository-install-dependencies

- name: repository | (keyrings) directory | create
  ansible.builtin.file:
    path: "{{ yarn_keyring_dst | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - yarn-repository-keyrings-directory-create

- name: repository | (keyring) file | download  # noqa command-instead-of-module risky-shell-pipe
  ansible.builtin.shell: >
    wget -O- {{ yarn_keyring_src }} | gpg --dearmor --yes --output {{ yarn_keyring_dst }}
  args:
    creates: "{{ yarn_keyring_dst }}"
  tags:
    - yarn-repository-keyring-file-download

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
    mode: '0644'
  with_items: "{{ yarn_repositories }}"
  tags:
    - yarn-repository-add
